name: itspark
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  image_picker: ^1.0.1
  modal_progress_hud_nsn: ^0.4.0
  gallery_saver: ^2.3.2
  sqflite: ^2.3.0
  dropdown_button2: ^1.9.2
  external_path: ^1.0.3
  webview_flutter: ^4.2.2
  easy_localization: ^3.0.2
  get: ^4.6.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  country_calling_code_picker: ^2.0.1
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  animated_splash_screen: ^1.3.0
  dartz: ^0.10.1
  get_it: ^7.6.0
  dotted_border: ^2.0.0+3
  intl: ^0.18.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  image: assets/images/logo.jpeg
  color: "#FFFFFF"
  android_gravity: center
  ios: true
#  ios_content_mode: center


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
